### PR TITLE
Added option for custom context functions

### PR DESCRIPTION
**Pull request by lukas-gitl**
Very useful if you want to use stuff like
`context.getRemainingTimeInMillis();`
http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html

### CODE REVIEW

**Comment by hassankhan** [comment]
Massive +1! 

Could it please match the same order as Lambda handlers i.e. `function(event, context, cb)`?

**Comment by lukas-gitl** [comment]
Well, I didn't want to break backwards compatibility. But we could detect the order by type and switch the parameters around?

**Comment by hassankhan** [comment]
Perhaps something like unshifting the last provided argument so it's always the callback? Although I'm not sure if that's best practice

**Comment by mpuittinen** [comment]
Does the context need to be in the run function call? Could it be moved to the object initialization to be passed in an options object?

var Lambda = require('lambda-wrapper').wrapped(mod, {
  context: myContext
});

This would be more versatile and extendible.

**Comment by mpuittinen** [comment]
Or in case the "custom" context is generic / compliant with the AWS context, one approach would be to add the missing methods to the default context method. That would be my preferred approach.

**Comment by hassankhan** [comment]
As I mentioned before, I believe it would make more sense to keep it consistent with existing Lambda function signatures. 

I don't quite understand what you mean by missing methods on the default context, could you explain it a bit more, please? As far as I'm aware, `context` has no methods, it is just a simple Javascript object.

**Comment by mpuittinen** [comment]
The lambda-wrapper module was initially implemented to ease writing of tests on lambda functions. The context was omitted on purpose to simplify the use and remove the need to define the context module on every single test module written. 

The current lambda wrapper mimics the function signature of the AWS-SDK method for invoking Lambda functions rather than the internal function structure of Lambda functions (see http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#invoke-property) If the full lambda signature is needed for some reason, I'd rather have that in a separate function rather than overloading the run method with new parameters.

**Comment by mpuittinen** [comment]
Is the need to truly have a "custom" context object or to have more functionality (mimic the full context implementation in AWS Lambda runtime) in the default context object? If the case is the later, I'd rather have the additional functionality in the default context object.

**Comment by hassankhan** [comment]
For my use case, I need to fake some Cognito identity parameters. AWS provides quite a few if memory serves correctly, I only need a few of them.

If a separate method is provided (`runWithContext` or similar) I'd love to use that. I'm currently blocked on writing tests at all, so would be super super happy if something could be merged ASAP 😄

**Comment by mpuittinen** [comment]
I merged the change and applied some changes. The custom context can be passed using the runHandler(event, context, callback) method. The original run method is just a wrapper for this new method. See README for more details.
The change is available in the latest module version (0.1.1)

**Comment by hassankhan** [comment]
Awesome, thank you so so much for merging it so quickly!!

**Pull request merged**
