### PR TITLE
Support custom handler names #4

### PR DESCRIPTION
**Pull request by johncmckim**
#4

### CODE REVIEW

**Comment by mpuittinen** [comment]
Hi! Could this be changed so that the alternative handler is passed in an options object during the Wrapped object intitialization, i.e.

var Lambda = require('lambda-wrapper').wrapped(mod, {
  handler: 'myhandler'
});

This would be more versatile and extendible.

**Comment by mpuittinen** [comment]
@johncmckim I've pushed an alternate implementation for your request. Can you please check whether that satisfies your need.

**Comment by johncmckim** [comment]
Thanks @mpuittinen looks perfect. Is the alternate on npm?

**Comment by mpuittinen** [comment]
Yep. It should be in the latest version of the lambda-wrapper module.

-Mikael

**Comment by johncmckim** [comment]
@mpuittinen found it and using it. Thanks again. Works perfectly.

**Pull request closed without merging**
